version: "1.0"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server:latest"
        environment:
            
            MSSQL_SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
       
            ports: -"1433:1433"